### ISSUE TITLE
Rename to nrf9160-pac

### ISSUE THREAD

**Issue by thejpster** [themadinventor/nrf91-rs#4]
We should rename this in advance of any new members of the nRF91 family appearing.

**Comment by thejpster** [comment]
Can an owner rename this repo please?

**Comment by hannobraun** [comment]
@thejpster I've made @nrf-rs/nrf91 an admin on this repository, which means you should be able to rename it. (I could do it myself, but I want to make sure I've set the permission correctly.)

**Comment by thejpster** [comment]
Tickety tick tick :)
